<script setup lang="ts">
import { ref, computed, watch, watchEffect } from 'vue'
import { Loader2, ArrowRight, ArrowLeft, Check } from 'lucide-vue-next'
import { StepperRoot, StepperItem, StepperTrigger, StepperIndicator, StepperTitle, StepperSeparator } from 'radix-vue'
import type { CatalogItemDTO, ProfileDTO, ProposalDTO } from '../../types'
import { ProposalStatus, PaymentMethod, SendMethod } from '../../types/enums'
import ProposalStepClient from './proposal/ProposalStepClient.vue'
import ProposalStepScope from './proposal/ProposalStepScope.vue'
import ProposalStepPayment from './proposal/ProposalStepPayment.vue'
import ProposalStepSummary from './proposal/ProposalStepSummary.vue'

const props = defineProps<{
  initialData?: ProposalDTO
  prefilledItems?: any[]
  isEditing?: boolean
  isSubmitting?: boolean
}>()

const emit = defineEmits(['submit'])

const currentStep = ref(1)

const steps = [
  { step: 1, title: 'Cliente' },
  { step: 2, title: 'Serviços' },
  { step: 3, title: 'Finalização' },
  { step: 4, title: 'Resumo' }
]

const clientSearch = ref('')
const { data: clientsData, pending: pendingClients } = useLazyFetch<any>('/api/clients', {
  key: 'clients-search',
  query: computed(() => ({
    limit: 20,
    search: clientSearch.value
  })),
  watch: [clientSearch],
  server: false
})
const { data: profile } = useFetch<ProfileDTO>('/api/profile', { key: 'profile' })
const { notify } = useAlerts()

const clients = computed(() => clientsData.value?.items || [])

const catalogSearch = ref('')
const catalogPage = ref(1)
const catalogLimit = 6

const { data: catalogData, refresh: refreshCatalog } = useFetch<any>('/api/catalog', {
  query: computed(() => ({
    page: catalogPage.value,
    limit: catalogLimit,
    search: catalogSearch.value
  })),
  watch: [catalogPage, catalogSearch]
})

const catalogItems = computed(() => catalogData.value?.items || [])
const totalCatalogItems = computed(() => catalogData.value?.total || 0)

const selectedClientId = ref('')

const form = ref({
  title: props.initialData?.title || '',
  status: props.initialData?.status || ProposalStatus.DRAFT,
  client: {
    name: props.initialData?.client?.name || '',
    email: props.initialData?.client?.email || '',
    phone: props.initialData?.client?.phone || ''
  },
  items: props.initialData?.items 
    ? [...props.initialData.items] 
    : (props.prefilledItems ? [...props.prefilledItems] : []) as any[],
  upsellItems: props.initialData?.upsellItems 
    ? [...props.initialData.upsellItems] 
    : [] as any[],
  totals: {
    additional: props.initialData?.totals?.additional || 0,
    discount: props.initialData?.totals?.discount || 0
  },
  paymentConfig: {
    method: props.initialData?.paymentConfig?.method || PaymentMethod.CASH,
    installments: props.initialData?.paymentConfig?.installments || 1,
    cashDiscount: props.initialData?.paymentConfig?.cashDiscount || 0
  },
  sendMethod: props.initialData?.sendMethod || SendMethod.AUTO,
  contractText: props.initialData?.contractText || '',
  termsAndConditions: props.initialData?.termsAndConditions || '',
  executionDate: props.initialData?.executionDate ? new Date(props.initialData.executionDate).toISOString().slice(0, 16) : ''
})

// Removed watch that forced #-ORC- prefix, as title is now generated by backend


// Carregar templates padrão se estiver vazio (novo orçamento)
watchEffect(() => {
  if (profile.value && !props.initialData?._id) {
    if (!form.value.contractText) form.value.contractText = profile.value.defaultContractTemplate
    if (!form.value.termsAndConditions) form.value.termsAndConditions = profile.value.defaultTermsAndConditions
    form.value.paymentConfig.installments = profile.value.defaultInstallments || 1
    form.value.paymentConfig.cashDiscount = profile.value.defaultCashDiscount || 0
  }
})

// Watch for initialData changes
watch(() => props.initialData, (newVal) => {
  if (newVal) {
    form.value = {
      title: newVal.title,
      status: newVal.status,
      client: { 
        name: newVal.client.name,
        email: newVal.client.email,
        phone: newVal.client.phone || ''
      },
      items: [...newVal.items],
      upsellItems: newVal.upsellItems ? [...newVal.upsellItems] : [],
      totals: {
        additional: newVal.totals?.additional || 0,
        discount: newVal.totals?.discount || 0
      },
      paymentConfig: {
        method: newVal.paymentConfig?.method || PaymentMethod.CASH,
        installments: newVal.paymentConfig?.installments || 1,
        cashDiscount: newVal.paymentConfig?.cashDiscount || 0
      },
      sendMethod: newVal.sendMethod || SendMethod.AUTO,
      contractText: newVal.contractText || '',
      termsAndConditions: newVal.termsAndConditions || '',
      executionDate: newVal.executionDate ? new Date(newVal.executionDate).toISOString().slice(0, 16) : ''
    }
  }
}, { deep: true })

watch(() => props.prefilledItems, (newVal) => {
  if (newVal && !props.initialData) {
    form.value.items = [...newVal]
  }
}, { deep: true })

const isGenerating = ref(false)

async function generateDescription({ index, isUpsell }: { index: number, isUpsell: boolean }) {
  const item = isUpsell ? form.value.upsellItems[index] : form.value.items[index]
  if (!item.name) return notify('Aviso', 'O item precisa de um nome para gerar a descrição.')
  
  isGenerating.value = true
  try {
    const prompt = `Gere uma descrição profissional para um serviço/produto chamado: ${item.name}`
    const data: any = await $fetch('/api/ai/generate', {
      method: 'POST',
      body: { prompt }
    })
    item.description = data.text
  } catch (e) {
    notify('Erro', 'Erro ao gerar descrição')
  } finally {
    isGenerating.value = false
  }
}

const finalTotal = computed(() => {
  const subtotal = form.value.items.reduce((acc, i) => acc + (i.price * i.quantity), 0)
  const baseTotal = subtotal + form.value.totals.additional - form.value.totals.discount
  
  if (form.value.paymentConfig.method === PaymentMethod.CASH) {
    return baseTotal * (1 - (form.value.paymentConfig.cashDiscount / 100))
  }
  return baseTotal
})

function validateStep(step: number): boolean {
  if (step === 1) {
    if (!form.value.client.name.trim()) {
      notify('Aviso', 'Nome do cliente é obrigatório')
      return false
    }
    if (!form.value.client.email.trim()) {
      notify('Aviso', 'E-mail do cliente é obrigatório')
      return false
    }
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(form.value.client.email)) {
      notify('Aviso', 'E-mail informado é inválido')
      return false
    }
  }

  if (step === 2) {
    if (form.value.items.length === 0) {
      notify('Aviso', 'Adicione pelo menos um item obrigatório ao escopo')
      return false
    }
    const allItems = [...form.value.items, ...form.value.upsellItems]
    for (const item of allItems) {
      if (!item.name.trim()) {
        notify('Aviso', 'Todos os itens precisam de um nome')
        return false
      }
      if (item.price < 0) {
        notify('Aviso', 'O preço não pode ser negativo')
        return false
      }
      if (item.quantity <= 0) {
        notify('Aviso', 'A quantidade deve ser maior que zero')
        return false
      }
    }
  }

  return true
}

function nextStep() {
  if (validateStep(currentStep.value)) {
    if (currentStep.value < steps.length) {
      currentStep.value++
    }
  }
}

function prevStep() {
  if (currentStep.value > 1) {
    currentStep.value--
  }
}

async function submit(status: ProposalStatus = ProposalStatus.DRAFT) {
  // Validate all steps before submitting
  if (!validateStep(1) || !validateStep(2)) return
  
  if (form.value.paymentConfig.installments < 1 || form.value.paymentConfig.installments > 12) {
    return notify('Aviso', 'O número de parcelas deve ser entre 1 e 12')
  }

  if (form.value.paymentConfig.cashDiscount < 0 || form.value.paymentConfig.cashDiscount > 100) {
    return notify('Aviso', 'O desconto deve estar entre 0% e 100%')
  }

  const keepStatus = props.isEditing && props.initialData?.status !== ProposalStatus.DRAFT
  const payload = keepStatus ? form.value : { ...form.value, status }
  emit('submit', payload)
}

defineExpose({
  submit,
  currentStep,
  prevStep,
  nextStep,
  totalSteps: steps.length,
  isEditingNonDraft: computed(() => props.isEditing && props.initialData?.status !== ProposalStatus.DRAFT),
  finalTotal
})
</script>

<template>
  <div class="flex flex-col gap-8">
    <!-- Radix Vue Stepper -->
    <StepperRoot v-model="currentStep" class="flex w-full gap-2 mt-2">
      <StepperItem
        v-for="step in steps"
        :key="step.step"
        class="relative flex w-full items-center justify-center"
        :step="step.step"
        :disabled="step.step > currentStep"
      >
        <StepperSeparator
          v-if="step.step !== steps.length"
          class="absolute left-[calc(50%+20px)] right-[calc(-50%+10px)] top-5 block h-[2px] shrink-0 rounded-full bg-gray-100 data-[state=completed]:bg-blue-600 transition-colors"
        />

        <StepperTrigger as="button" class="flex flex-col items-center text-center gap-2 rounded-md outline-none focus-visible:ring-2 focus-visible:ring-blue-600">
          <StepperIndicator
            :class="[
              'flex h-10 w-10 items-center justify-center rounded-full text-sm font-black border-2 transition-all',
              currentStep === step.step ? 'border-blue-600 bg-blue-600 text-white shadow-lg shadow-blue-200' :
              currentStep > step.step ? 'border-blue-600 bg-blue-600 text-white' : 'border-gray-200 text-gray-400 bg-white'
            ]"
          >
            <Check v-if="currentStep > step.step" class="w-5 h-5" />
            <span v-else>{{ step.step }}</span>
          </StepperIndicator>
          <div class="space-y-0.5">
            <StepperTitle :class="['text-xs font-black uppercase tracking-widest', currentStep >= step.step ? 'text-gray-900' : 'text-gray-400']">
              {{ step.title }}
            </StepperTitle>
          </div>
        </StepperTrigger>
      </StepperItem>
    </StepperRoot>

    <!-- Content Area -->
    <form @submit.prevent="submit" class="pb-6">
      <div class="min-h-[40vh]">
        <ProposalStepClient 
          v-show="currentStep === 1"
          :form="form"
          :clients="clients"
          :pending="pendingClients"
          v-model:selectedClientId="selectedClientId"
          v-model:clientSearch="clientSearch"
        />

        <ProposalStepScope 
          v-show="currentStep === 2"
          :form="form"
          :catalog-items="catalogItems"
          :total-catalog-items="totalCatalogItems"
          v-model:catalogSearch="catalogSearch"
          :is-generating="isGenerating"
          @generate-description="generateDescription"
          @catalog-updated="refreshCatalog"
        />

        <ProposalStepPayment 
          v-show="currentStep === 3"
          :form="form"
          :final-total="finalTotal"
        />

        <ProposalStepSummary 
          v-show="currentStep === 4"
          :form="form"
          :final-total="finalTotal"
          :clients="clients"
        />
      </div>

    </form>
  </div>
</template>
